### ISSUE TITLE
wget to releases failed; unsure if it's my config or not

### ISSUE THREAD

**Issue by cryptowally** [e-COSI/docker-bastillion#3]
I tried to load this up with the Dockerfile that came with it, but it failed during the first wget.

I updated the ARG section of the dockerfile to this:

```
ARG BASTILLION_VERSION="3.09.00"
ARG BASTILLION_FILENAME_VERSION="3.09_00"
ARG DOCKERIZE_VERSION="0.6.1"
```

since those are the latest versions I could find, and then it built.

Is the Dockerfile, or parent host somehow supposed to supply these environment variables?
```
ENV BASTILLION_VERSION=${BASTILLION_VERSION} \
    BASTILLION_FILENAME=${BASTILLION_FILENAME_VERSION} \
    DOCKERIZE_VERSION=${DOCKERIZE_VERSION}
```

btw, I'm launching this via `docker-compose` instead of `docker run` so I can bundle it with nginx more easily.  Not sure if that's relevant or not.

I cloned this repo into the directory and renamed it to "bastillion-docker"

docker-compose.yml:
```
---
version: '2'

services:
  bastillion:
    container_name: bastillion
    build: bastillion-docker
    volumes:
      - ./keydb:/opt/bastillion/jetty/bastillion/WEB-INF/classes/keydb
    restart: always

  proxy:
    container_name: proxy
    build: proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - bastillion
```

The nginx proxy forwards 80-->8080 and 443->8443 but I don't have that part working yet.  For now I just want bastillion running, and then I'll customize further for HTTPS, custom SSH keys, etc.
